use-grammars = { only = [ 
  "rust",
  "c",
  "cpp",
  "html",
  "javascript",
  "css",
  "elisp",
  "markdown",
  "xml",
  "org",
  "json",
  "yaml",
  "toml",
  "dockerfile",
  "bash",
  "lua",
  "meson",
  "make",
  "ini",
  "git-commit",
  "git-config",
  "git-rebase"
  ]}
